### PR TITLE
cp README -> vignette

### PR DESCRIPTION
**Pull request by mpadge**

### CODE REVIEW

**Comment by layik** [comment]
```
Error: processing vignette 'stats19.Rmd' failed with diagnostics:
there is no package called 'ukboundaries'```

I wish we did not have to add dependencies but leave that to you @mpadge

**Comment by Robinlovelace** [comment]
@mpadge still not passing seemingly.

**Comment by layik** [comment]
Should not be failing now really. Added a new GITHUB_PAT.

**Comment by layik** [comment]
I *think* I will approve this if the other PR succeeds. It would then mean a merge and hopefully a pass on the master.

**Comment by layik** [comment]
aaah, was a little too certain, now fails on `tidyverse`. See if I can add an install for the vignette.

**Comment by Robinlovelace** [comment]
Doh! You could use `require()` to only run chunks if the **tidyverse** is installed...

**Comment by layik** [comment]
Do you want to try and do this @Robinlovelace?

**Comment by Robinlovelace** [comment]
Not atm. Should have passed before this was accepted.

**Comment by layik** [comment]
I know, it is my fault. Let me sort it out :)

**Comment by mpadge** [comment]
Nah, that's all my fault, please just add the `tidyverse` components (I think it's just `dplyr` and `tidyr`?) to `Suggests` - not to `Imports`, so no package bloat at all

**Comment by Robinlovelace** [comment]
Correct: `tidyr` and `dplyr` are the pkgs used. And `ggplot2`. Happy with them as `Suggests`.

**Comment by layik** [comment]
all good gents, I think I got this.

**Comment by layik** [comment]
One kind not @mpadge, if we send the PR's as branches, we can all push to them.

**Comment by layik** [comment]
all good I think, its now easier with a PR 
https://travis-ci.org/ITSLeeds/stats19/builds/470956046#L1944

**Comment by layik** [comment]
OK, waiting for this, did not know `suggest` can solve such issues. So learned something
https://github.com/ITSLeeds/stats19/commit/983f9e5446cfb007937f6113ee6478826a77580a

**Comment by layik** [comment]
there is much more to this
`stringr`

**Comment by layik** [comment]
Finally!

**Comment by layik** [comment]
I think it is safe to leave them in suggests.
http://r-pkgs.had.co.nz/description.html#dependencies

**Pull request merged**
