### PR TITLE
add data-raw with schema.Rmd script

### PR DESCRIPTION
**Pull request by mpadge**
@layik This is what Adam meant in the review. This stuff about creating the schema doesn't need to be exposed to the end user, so is better off stuck in `data-raw`, which remains "hidden" to all but those who are genuinely interested.

### CODE REVIEW

**Comment by Robinlovelace** [comment]
@mpadge an additional advantage is that this can reduce the dependencies. We can remove `readxl` from the DESCRIPTION now I think.

**Comment by mpadge** [comment]
Oh yeah, totally true. I'll leave that to you... Thanks

**Comment by adamhsparks** [comment]
Exactly what I had meant, @mpadge. Thanks for implementing this, everyone.

**Comment by mpadge** [comment]
Yeah, no worries @adamhsparks. This has all been really interesting for me, because it's been my first truly team-centered collaborative development. Makes me realise there is actually quite a need for some kind of "good enough practice" guidelines for **collaborative** development. I'm making that note buried here until one of us acts upon it at a later point ...

## Future TODO list

- [ ] Good enough practice guidelines for **collaborative** development

Ping @sckott, just coz maybe something like this already exists in the bowels of ROpenSci? Or @stefaniebutland - maybe a blog entry?

**Comment by stefaniebutland** [comment]
Thanks for the ping @mpadge! Are you suggesting you might have something to say in a blog post? 😀 🙏 Or maybe in https://discuss.ropensci.org/ is a good place to get others to weigh in on their experiences, while being less formal. 

I'll see what Scott has to say about existing info

**Comment by adamhsparks** [comment]
I hear you. bomrang was like that for me and still is with the active
contributors. It takes a different mindset to work in and lead something
like that.

-- 
Adam H Sparks

**Comment by stefaniebutland** [comment]
Rather than aiming for a detailed/time-consuming set of guidelines, @mpadge do you think you might do a "brain dump" of your thoughts in the forum? (I know Noam Ross says he uses the forum when he doesn't have the time for a full post) Maybe in https://discuss.ropensci.org/c/best-practices? Perhaps @adamhsparks could chime in and then rOpenSci can tweet a link to the discussion to get more comments. Seems like a topic people would want to hear/read about. Reminds me of this one that got > 40 comments: https://discuss.ropensci.org/t/how-do-you-review-code-that-accompanies-a-research-project-or-paper-help-ropensci-plan-a-community-call/1321/51

Ultimately a blog post could come of it...or not, depending on how ambitious people feel

Either way, no obligation. Thanks for tagging us

**Pull request merged**
