### PR TITLE
allow multiple file downloads

### PR DESCRIPTION
**Pull request by mpadge**
@layik @Robinlovelace Don't merge this yet, but this is a first response to my very first usage of the package. Doing so prompted the question of why the heck I couldn't just download data for a range of years, and so this code now allows that.

It then breaks most subsequent code, because that expects to handle just single years, but I first wanted to discuss here whether this was okay. I may have misunderstood and perhaps there was a reason why you were only permitting single years to be downloaded? But the code here works, and successfully downloads data for multiple years.

You can now do this:
```
dl_stats19(years = 2011:2017, type = "a")
```
A couple of other things have also been changed, including
1. proper sanity check on the "type" argument
2. auto-creation of `data_dir` if it does not exist

Thoughts?

### CODE REVIEW

**Comment by mpadge** [comment]
Oh, and another change was to just extract the data straight into `data_dir`, rather than the subdirs, and also to auto-remove the `.zip` and leave just the extracted `.csv`s.

**Comment by Robinlovelace** [comment]
What would you recommend in cases where 2 downloaded files had the same name? I think the folder/file names are unique but not the file names alone.

**Comment by layik** [comment]
Great work Mark, thanks Robin.

1. In principle, this is where we should be going next (definitely). The reason why I code so is because R is still not my default style of coding. I think I know the reason why I defaulted to single file downloads but not necessary here.
2. As Robin just commented that is an enough good reason for keeping the directory structure intact, there is more.
3. As for the other minor matters (1 and 2) I think the unzip does write to the `-p` underneath to create the `data_dir` if it does not exist. If not definitely needs to go in. Sanity checks, I am still learning R.

Finally, I think this is a great piece of work, could we submit to CRAN as it is and then make the changes without breaking the functions already in? Get a simple/robust package in and then add functionality.

**Comment by layik** [comment]
https://github.com/ITSLeeds/stats19/issues/18 deals with `.zip` cleanup.

**Comment by mpadge** [comment]
rOpenSci now have quite a clear policy [smarter me inserts link here, but I can't find it right now] that they prefer packages to be reviewed first prior to CRAN submission. It's no issue done the other way, but they have enough experience now to prefer rOpenSci -> CRAN rather than the other way around.

**Comment by Robinlovelace** [comment]
> rOpenSci now have quite a clear policy [smarter me inserts link here, but I can't find it right now] that they prefer packages to be reviewed first prior to CRAN submission. It's no issue done the other way, but they have enough experience now to prefer rOpenSci -> CRAN rather than the other way around.

Good to know. It's in the process and I've suggested reviewers.

**Comment by mpadge** [comment]
Shall I fix thus up ready for merge then? (That will primarily involve letting downstream functions handle multiple files).

**Comment by Robinlovelace** [comment]
Sure that would be greatly appreciated. But as discussed with @layik it's not a priority (higher priority I would say is feedback on the vignette - e.g. does it make sense?!)

**Comment by Robinlovelace** [comment]
A wider point is that https://github.com/departmentfortransport are planning to release an API that should make downloading data easier. The main point is that you *can* download whichever dataset much easier than before. It could be made *even* easier but not sure if the marginal benefits will be worth the time costs of all that. May be one that we'll hear more views on from an rOpenSci review.

**Comment by layik** [comment]
IF the issue is multiple file download, we can definitely do this simpler than the overhaul. Again, I suggest we keep this for later and get on with getting the data on a server and start consuming it.

**Pull request closed without merging**
